### ISSUE TITLE
Update MSRV to 1.70.0

### ISSUE THREAD

**Issue by mooori** [aurora-is-near/near-plugins#121]
Currently we still need to support Rust 1.69.0 for some users of this library. Once they are fine with upgrading to 1.70.0, we should bump `near-plugin`’s MSRV.

**Reason**: Using `near-workspaces` with Rust 1.69.0 requires manually downgrading some dependencies, which is bad developer experience and requires maintenance. (See the conversation in #118).

**Tasks**:

- [ ] Bump `rust-version` in `./Cargo.toml` and `channel` in `./rust-toolchain`
- [ ] Build test contracts with the new MSRV: bump `channel` in `./near-plugins-derive/tests/contracts/**/rust-toolchain`
- [ ] Remove `./scripts/fix-dependencies.sh`
  - [ ] Stop executing that script in CI
